import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Liav Edry | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://use.fontawesome.com/releases/v5.6.4/css/all.css" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello, I&apos;m Liav Edry
        </h1>
        <h2 className={styles.subtitle}>
          Web Developer
        </h2>
        <code className={styles.tagline}>Software Engineer &amp;&amp; Next.js || JavaScript</code>
      </main>
    </div>
  )
}
