import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Liav Edry | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://use.fontawesome.com/releases/v5.6.4/css/all.css" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello, I&apos;m Liav Edry
        </h1>
        <code className={styles.tagline}>Web Developer &amp;&amp; Next.js || JavaScript</code>
        <div className={styles.iconsSocials}>
          <a target="_blank" title="GitHub Profile" href="https://github.com/Devail1"><i className="fab fa-github"></i></a>
          <a target="_blank" title="LinkedIn Profile" href="https://www.linkedin.com/in/liav-edry/"><i className="fab fa-linkedin"></i></a>
        </div>
      </main>
    </div>
  )
}
