import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Liav Edry | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://use.fontawesome.com/releases/v5.6.4/css/all.css" rel="stylesheet" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Hello, I&apos;m Liav Edry</h1>
        <code className={styles.tagline}>
          Web Developer &amp;&amp; MERN || Next.js 14 || TypeScript
        </code>
        <div className={styles.iconsSocials}>
          <a
            target="_blank"
            title="GitHub Profile"
            rel="noreferrer"
            href="https://github.com/Devail1"
          >
            <i className="fab fa-github" />
          </a>
          <a
            target="_blank"
            title="LinkedIn Profile"
            rel="noreferrer"
            href="https://www.linkedin.com/in/liav-edry/"
          >
            <i className="fab fa-linkedin" />
          </a>
        </div>
      </main>
    </div>
  );
}
